version: '3.8'

services:
    db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./db.env
      container_name: mango-db

    nginx:
      build: ./nginx
      ports:
        - '80:80'
      volumes:
        - gunicorn:/mango/run
        - static:/var/www/static
        - media:/var/www/media
      depends_on:
        - mango
      restart: "on-failure"

    app:
      build: ./mango
      restart: always
      volumes:
        - gunicorn:/mango/run
        - static:/var/www/static
        - media:/var/www/media

      env_file:
        - ./mango.env
      depends_on:
        - db
      container_name: mango




volumes:
    postgres_data:
    gunicorn:
    static:
    media: